### ISSUE TITLE
Link for site needs to point to https://puruvjdev4.pages.dev/

### ISSUE THREAD

**Issue by spences10** [PuruVJ/puruvjdev4#8]
currently pointing to Vercel still

guessed you where on CF when saw switch to cf in commits

also, about time you made a blog post! 😂

**Comment by PuruVJ** [comment]
Wait where is it pointing to vercel? 

Also it shouldn't point to cf pages, it's just vps now

**Comment by spences10** [comment]
![image](https://github.com/PuruVJ/puruvjdev4/assets/234708/1b2b1046-eeb5-4f65-bfe7-88489ae44d66)

Guess [puruvjdev4.pages.dev](https://puruvjdev4.pages.dev) is still cached then?
